"""قرارات اختبار واقعية فوق risk_fixture (TODAY = 2026-09-30)."""
def decisions():
    H = lambda *ev: [{"event": e, "actor": a, "at": t} for e, a, t in ev]
    return [
        {"id": 1, "title": "إعادة التفاوض مع المورد الرئيسي", "rationale": "ارتفاع تكلفة الشراء", "category": "supplier", "priority": "high", "source": "risk_driver",
         "workflow": "measured", "owner": "مدير المشتريات", "due": "2026-04-30", "created_at": "2026-03-05", "approved_at": "2026-03-06", "completed_at": "2026-04-20",
         "expected_impact": 200000, "cost": 20000, "risk_key": "supplier_concentration_pct", "risk_baseline": 74, "root_cause": "cost_increase_pct", "root_cause_baseline": 95,
         "kpis": [{"id": 1, "metric": "gross_margin", "target": 40}, {"id": 2, "metric": "on_time", "baseline": 80, "side_effect": True}],
         "outcome": {"measured_at": "2026-08-15"}, "history": H(("created", "سعود", "2026-03-05 09:30"), ("approved", "سعود", "2026-03-06 12:00"), ("completed", "مدير المشتريات", "2026-04-20"), ("measured", "سعود", "2026-08-15"))},
        {"id": 2, "title": "تعديل سياسة الخصم", "rationale": "خصومات فوق المعتاد", "category": "discount", "priority": "medium", "source": "leakage", "workflow": "completed",
         "owner": "مدير المبيعات", "due": "2026-03-31", "created_at": "2026-02-01", "approved_at": "2026-02-02", "completed_at": "2026-03-15", "expected_impact": 150000,
         "kpis": [{"id": 3, "metric": "revenue", "target": 160000}], "history": H(("created", "سعود", "2026-02-01"))},
        {"id": 3, "title": "اعتماد مورد بديل", "rationale": "تركز الموردين", "category": "supplier", "priority": "high", "source": "risk", "workflow": "in_progress",
         "owner": "مدير المشتريات", "due": "2026-09-01", "created_at": "2026-07-01", "approved_at": "2026-07-02", "expected_impact": 280000, "delay_reason": "supplier",
         "kpis": [{"id": 4, "metric": "supplier_late_pct", "baseline": 20, "target": 5}], "actions": [{"id": 1, "title": "طلب عروض", "owner": "مدير المشتريات", "status": "in_progress", "progress": 40}],
         "history": H(("created", "سعود", "2026-07-01"), ("approved", "سعود", "2026-07-02"))},
        {"id": 4, "title": "زيادة موظفين في فرع جدة", "rationale": "ضغط التشغيل", "category": "staffing", "priority": "medium", "source": "manual", "workflow": "pending_approval",
         "owner": "مدير جدة", "branch": "جدة", "due": "2026-11-15", "created_at": "2026-09-10", "expected_impact": 40000, "kpis": [{"id": 5, "metric": "revenue", "target": 50000}],
         "history": H(("created", "مدير جدة", "2026-09-10"), ("submitted", "مدير جدة", "2026-09-12"))},
        {"id": 5, "title": "خفض المصروفات التشغيلية", "category": "cost", "workflow": "draft", "created_at": "2026-09-25", "kpis": []},
        {"id": 6, "title": "معالجة المصروفات الزائدة", "rationale": "تسرب مصروفات", "category": "leakage", "source": "leakage", "workflow": "completed", "owner": "المالية",
         "due": "2026-08-15", "created_at": "2026-07-10", "approved_at": "2026-07-11", "completed_at": "2026-08-01", "expected_impact": 60000, "leakage_key": "opex",
         "leakage_baseline": 15000, "kpis": [{"id": 6, "metric": "expense_ratio", "target": 25}], "sensitive": True},
        {"id": 7, "title": "إطلاق عرض ترويجي", "category": "marketing", "workflow": "approved", "owner": "التسويق", "due": "2026-12-01", "created_at": "2026-09-20",
         "approved_at": "2026-09-21", "expected_impact": 30000, "depends_on": [3], "kpis": [{"id": 7, "metric": "revenue"}]},
        {"id": 8, "title": "مراجعة أسعار الموردين", "category": "supplier", "workflow": "measured", "created_at": "2025-12-01", "completed_at": "2025-12-20", "owner": "المشتريات",
         "kpis": [{"id": 8, "metric": "cost_increase_pct", "baseline": 3}], "expected_impact": 50000, "outcome": {"actual_manual": 10000, "notes": "فاتورة المورد"}},
        {"id": 9, "title": "مراجعة أسعار الموردين الربعية", "category": "supplier", "workflow": "measured", "created_at": "2026-04-01", "completed_at": "2026-04-20", "owner": "المشتريات",
         "kpis": [{"id": 10, "metric": "cost_increase_pct", "baseline": 8}]},
        {"id": 11, "title": "تجربة تسعير ملغاة", "category": "pricing", "workflow": "cancelled", "created_at": "2026-05-01", "kpis": []},
        {"id": 10, "title": "مراجعة أسعار الموردين مجدداً", "category": "supplier", "workflow": "approved", "created_at": "2026-08-01", "approved_at": "2026-08-02",
         "owner": "المشتريات", "due": "2026-10-30", "kpis": [{"id": 9, "metric": "cost_increase_pct", "baseline": 25}], "goal_id": 2,
         "goal_baseline": {"status": "at_risk", "progress": 0.2, "expected_gap": 100000}},
    ]
